### ISSUE TITLE
[外部提案] SEO強化してGoogleからアクセスし易いようにする。

### ISSUE THREAD

**Issue by wizardry** [kumamotone/gfdm-skill#1]
* webmasterツールとの連携、各サーチエンジン登録
* description,title,その他見出しなどマークアップによるSEO対策
* sitemap.xmlの送信
* robotsの設定

など
[ギタドラ　シミュ],[GITADORA シミュ] あたりで10件以内に表示させたい。

**Comment by kumamotone** [comment]
数日経てば適当にクロールされるかな？と思いましたが，意外と上に来ないですね．非営利なのであまりガツガツしたくなかったですが[ギタドラ　シミュ]で上位に出ないのは個人的に使いづらくて困るのでせっかくなので対策しましょう．

質問なのですが，
* 登録するサーチエンジンはgoogle以外だと何処が考えられるでしょうか？
* robotsの設定はどのようにすると効果的でしょうか？

**Comment by y-takase** [comment]
すいません、質問見逃していました。

yahoo!
bing
にWebサイト登録だけしておくのがベターだと思います。

robotsは編集画面などクローラーbot巡回不要な画面につけるのがベターだと思います。

また、上記よりかはWebmasterツールでfetchしてあげる、googleが認識しているキーワードを確認し、コンテンツの文言を調整するほうが手っとり早く上がる気がします。

例えば量産されるであろうユーザーページにメインのキーワードを設置する、strongなどのタグを利用するなど...
他、イイネやツイッター拡散度もコンテンツの信頼度を計るのにみていたこともあるらしいので、ogタグやSNSボタンの設置などもSEOに繋がると思います。

**Comment by wizardry** [comment]
すいません、質問見逃していました。

yahoo!
bing
にWebサイト登録だけしておくのがベターだと思います。

robotsは編集画面などクローラーbot巡回不要な画面につけるのがベターだと思います。

また、上記よりかはWebmasterツールでfetchしてあげる、googleが認識しているキーワードを確認し、コンテンツの文言を調整するほうが手っとり早く上がる気がします。
例えば量産されるであろうユーザーページにメインのキーワードを設置するするなど...

他、
・イイネやツイッター拡散度もコンテンツの信頼度を計るのにみていたこともあるらしいので、ogタグやSNSボタンの設置などもSEOに繋がると思います。
・、strongなどのタグを利用することで気持ちクローラーbotに優しいつくりになるかもしれません

**Comment by kumamotone** [comment]
ご回答ありがとうございます．
ご指摘の通り以下やってみます．

* Yahoo!, bing への登録
* robots.txt で巡回不要なページを指定する

> ・イイネやツイッター拡散度もコンテンツの信頼度を計るのにみていたこともあるらしいので、ogタグやSNSボタンの設置などもSEOに繋がると思います。

SNS ボタンの設置，ある程度拡散されきった感あるので今更TOPに貼るのちょっと抵抗ありますが，各スキル表ページにツイートボタンあると便利かな？とは思ってたのでとりあえずそっちに貼ってみようかなと思います．

> ・strongなどのタグを利用することで気持ちクローラーbotに優しいつくりになるかもしれません

更新時に意識してみます．ありがとうございます．

何が直接的に効いたのかはよくわかりませんが，
現状ご指摘いただいた以下の項目については実践してみて，
おかげさまで sitemap.xml を提出したあたりからじわじわ１ページ目にも表示されるように
なってきたように見えます．
（推測ですが，TOPのリファラはFC2ブログからが圧倒的に多いでオーソリティが上がらず，各スキル表は各所に貼られるのでオーソリティが上がり，sitemap で各スキル表がサイトの一部であることを認識させることによってTOPのオーソリティが上昇した？）

* webmasterツールとの連携
* sitemap.xmlの送信
* robotsの設定
* トップページの文言を検索キーワードに引っかかりやすいように変更（GITADORA Tri-boost Skill Simulator → GITADORA　スキルシミュレータ　など）

**Comment by kumamotone** [comment]
以上以外特に何もやってないですが，
たぶん被リンクが自然に増えたからか，
「ギタドラ　スキル」「ギタドラ　シミュ」あたりのワードでは一番上でヒットするようになりました．
