### ISSUE TITLE
[外部提案] TOPデザインの見直し

### ISSUE THREAD

**Issue by wizardry** [kumamotone/gfdm-skill#2]
問題点
* 新規登録の位置がわかりにくい
* TOPコンテンツ内に新規登録、ログインの導線があるとコンバージョンがあがるのでは？

**Comment by kumamotone** [comment]
ありがとうございます．新規登録とログイン，確かにメニューは特にスマホとかだと折りたたまれちゃって見えないので，コンテンツ内に含めても良さそうですね．

**Comment by wizardry** [comment]
@kumamotone 
すいません、なんか思い立って一方的にだだっと立てまくりました。
※issueあった方が他者も参加しやすいかなとも思い…

TOPのファーストビュー上にあれば、もっとユーザー数増えるかと思います！
blogの方にも記載させていただいたのですが、使用技術やルールだけでもreadme.mbにまとめていただければ
他の方も参加しやすいかと思います！

**Comment by wizardry** [comment]
五月雨で申し訳ないですがreadme.mbじゃなくgithub wikiもありかもしれません！

**Comment by kumamotone** [comment]
@wizardry 
いえいえありがとうございます！
参加していただける人いるかわからないですが間違いなくそうだと思います．

さすがにソースコードはGithub上にありますって言っておいて readme.mb に何も書いてないのも無作法すぎると思うので何か書きますねｗ；
Github wiki というのもあるんですね　検討してみます
