### ISSUE TITLE
[外部提案] 外部リンクのtarget="_blank"化

### ISSUE THREAD

**Issue by wizardry** [kumamotone/gfdm-skill#3]
外部リンクをtarget="_blank"にする。

* 自ドメインコンテンツの遷移とそうでないものを明確に分ける。
* それが一般的と認識しているユーザーも居るため、遷移先で誤ってタブを閉じるなどの誤脱落を減らす。

**Comment by kumamotone** [comment]
なるほど，特に意識していなかったですがその方が自然な気もしますね．ひとまずそうしてみます．
